services:
  rank_keeper:
    build:
      context: ./src
      dockerfile: .dockerfile
    tty: true
    env_file:
      - .env
    working_dir: /bot/app
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./src:/bot
    depends_on:
      mysql:
        condition: service_healthy

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '127.0.0.1:50021:50021'
    tty: true
    healthcheck:
      test: ping 127.0.0.1:50021
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s