services:
  rank_keeper:
    build:
      context: ./src
      dockerfile: .dockerfile
    tty: true
    env_file:
      - .env
    working_dir: /bot/app
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./src:/bot
    depends_on:
      voicevox_engine:
        condition: service_started
    networks:
      - external

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '127.0.0.1:50021:50021'
    tty: true
    networks:
      - external

networks:
  external:
    driver: bridge
    external: true